language: node_js
node_js:
  - "12"
cache:
  yarn: true
  directories:
    - node_modules
install: yarn
script:
  - bash ./deploy/deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "583a5951da37"
    - COMMIT_AUTHOR_EMAIL: "amishshah.2k@gmail.com"
dist: bionic
sudo: false
