language: node_js
node_js:
  - "9"
cache:
  yarn: true
  directories:
    - node_modules
install: yarn
script:
  - bash ./deploy/deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "d9d8d4fbc4cd"
    - COMMIT_AUTHOR_EMAIL: "admin@opposite.biz"
dist: trusty
sudo: false
